// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Test_ONUS.Data;

#nullable disable

namespace Test_ONUS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260712144134_AddResetToken")]
    partial class AddResetToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Test_ONUS.Models.Atleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Altezza")
                        .HasColumnType("integer");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescrizioneInfortunio")
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAttivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInRiabilitazione")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInfortunato")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision");

                    b.Property<int>("SquadraId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SquadraId");

                    b.ToTable("Atleti");
                });

            modelBuilder.Entity("Test_ONUS.Models.Parametro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAttivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCalcoloCarico")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SquadraId")
                        .HasColumnType("integer");

                    b.Property<int>("ValoreMassimo")
                        .HasColumnType("integer");

                    b.Property<int>("ValoreMinimo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Parametri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAttivo = true,
                            IsCalcoloCarico = true,
                            Nome = "RPE",
                            ValoreMassimo = 10,
                            ValoreMinimo = 0
                        },
                        new
                        {
                            Id = 2,
                            IsAttivo = true,
                            IsCalcoloCarico = false,
                            Nome = "Sonno",
                            ValoreMassimo = 10,
                            ValoreMinimo = 0
                        },
                        new
                        {
                            Id = 3,
                            IsAttivo = true,
                            IsCalcoloCarico = false,
                            Nome = "Dolore",
                            ValoreMassimo = 10,
                            ValoreMinimo = 0
                        });
                });

            modelBuilder.Entity("Test_ONUS.Models.PreparatoreAtletico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetTokenScadenza")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SquadraId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SquadraId");

                    b.ToTable("PreparatoriAtletici");
                });

            modelBuilder.Entity("Test_ONUS.Models.SessioneAllenamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtletaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurataTotaleMinuti")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("TempoEffettivoMinuti")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Sessioni");
                });

            modelBuilder.Entity("Test_ONUS.Models.SottoscrizionePush", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtletaId")
                        .HasColumnType("integer");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.ToTable("SottoscrizioniPush");
                });

            modelBuilder.Entity("Test_ONUS.Models.Squadra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Squadre");
                });

            modelBuilder.Entity("Test_ONUS.Models.ValoreSessione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ParametroId")
                        .HasColumnType("integer");

                    b.Property<int>("SessioneId")
                        .HasColumnType("integer");

                    b.Property<int>("Valore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParametroId");

                    b.HasIndex("SessioneId");

                    b.ToTable("ValoriSessione");
                });

            modelBuilder.Entity("Test_ONUS.Models.Atleta", b =>
                {
                    b.HasOne("Test_ONUS.Models.Squadra", "Squadra")
                        .WithMany("Atleti")
                        .HasForeignKey("SquadraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Squadra");
                });

            modelBuilder.Entity("Test_ONUS.Models.PreparatoreAtletico", b =>
                {
                    b.HasOne("Test_ONUS.Models.Squadra", "Squadra")
                        .WithMany("Preparatori")
                        .HasForeignKey("SquadraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Squadra");
                });

            modelBuilder.Entity("Test_ONUS.Models.SottoscrizionePush", b =>
                {
                    b.HasOne("Test_ONUS.Models.Atleta", "Atleta")
                        .WithMany()
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");
                });

            modelBuilder.Entity("Test_ONUS.Models.ValoreSessione", b =>
                {
                    b.HasOne("Test_ONUS.Models.Parametro", "Parametro")
                        .WithMany()
                        .HasForeignKey("ParametroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Test_ONUS.Models.SessioneAllenamento", "Sessione")
                        .WithMany("Valori")
                        .HasForeignKey("SessioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parametro");

                    b.Navigation("Sessione");
                });

            modelBuilder.Entity("Test_ONUS.Models.SessioneAllenamento", b =>
                {
                    b.Navigation("Valori");
                });

            modelBuilder.Entity("Test_ONUS.Models.Squadra", b =>
                {
                    b.Navigation("Atleti");

                    b.Navigation("Preparatori");
                });
#pragma warning restore 612, 618
        }
    }
}
