// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Test_ONUS.Data;

#nullable disable

namespace Test_ONUS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260611183449_AddPushSubscriptions")]
    partial class AddPushSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Test_ONUS.Models.Atleta", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Cognome")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("SquadraId")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("SquadraId");

                b.ToTable("Atleti");
            });

            modelBuilder.Entity("Test_ONUS.Models.Parametro", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("TipologiaValore")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Parametri");
            });

            modelBuilder.Entity("Test_ONUS.Models.PreparatoreAtletico", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Cognome")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Preparatori");
            });

            modelBuilder.Entity("Test_ONUS.Models.SessioneAllenamento", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("AtletaId")
                    .HasColumnType("integer");

                b.Property<string>("Data")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("AtletaId");

                b.ToTable("Sessioni");
            });

            modelBuilder.Entity("Test_ONUS.Models.SottoscrizionePush", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("AtletaId")
                    .HasColumnType("integer");

                b.Property<string>("Auth")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Endpoint")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("P256dh")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("AtletaId");

                b.ToTable("SottoscrizioniPush");
            });

            modelBuilder.Entity("Test_ONUS.Models.Squadra", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Squadre");
            });

            modelBuilder.Entity("Test_ONUS.Models.ValoreSessione", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("ParametroId")
                    .HasColumnType("integer");

                b.Property<int>("SessioneId")
                    .HasColumnType("integer");

                b.Property<string>("Valore")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("ParametroId");

                b.HasIndex("SessioneId");

                b.ToTable("ValoriSessione");
            });

            modelBuilder.Entity("Test_ONUS.Models.Atleta", b =>
            {
                b.HasOne("Test_ONUS.Models.Squadra", "Squadra")
                    .WithMany("Atleti")
                    .HasForeignKey("SquadraId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Squadra");
            });

            modelBuilder.Entity("Test_ONUS.Models.SessioneAllenamento", b =>
            {
                b.HasOne("Test_ONUS.Models.Atleta", "Atleta")
                    .WithMany()
                    .HasForeignKey("AtletaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Atleta");
            });

            modelBuilder.Entity("Test_ONUS.Models.SottoscrizionePush", b =>
            {
                b.HasOne("Test_ONUS.Models.Atleta", "Atleta")
                    .WithMany()
                    .HasForeignKey("AtletaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Atleta");
            });

            modelBuilder.Entity("Test_ONUS.Models.ValoreSessione", b =>
            {
                b.HasOne("Test_ONUS.Models.Parametro", "Parametro")
                    .WithMany()
                    .HasForeignKey("ParametroId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Test_ONUS.Models.SessioneAllenamento", "Sessione")
                    .WithMany("Valori")
                    .HasForeignKey("SessioneId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Parametro");

                b.Navigation("Sessione");
            });

            modelBuilder.Entity("Test_ONUS.Models.SessioneAllenamento", b =>
            {
                b.Navigation("Valori");
            });

            modelBuilder.Entity("Test_ONUS.Models.Squadra", b =>
            {
                b.Navigation("Atleti");
            });
#pragma warning restore 612, 618
        }
    }
}